package com.dinnerorders.domain;

import java.util.ArrayList;
import java.util.List;

public class GroupWithUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.desciption
     *
     * @mbggenerated
     */
    private String desciption;
    
    private List<User> users = new ArrayList<User>();

    public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.desciption
     *
     * @return the value of groups.desciption
     *
     * @mbggenerated
     */
    public String getDesciption() {
        return desciption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.desciption
     *
     * @param desciption the value for groups.desciption
     *
     * @mbggenerated
     */
    public void setDesciption(String desciption) {
        this.desciption = desciption == null ? null : desciption.trim();
    }
}