package com.dinnerorders.dao;

import com.dinnerorders.domain.Dish;
import com.dinnerorders.domain.DishExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int countByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int deleteByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int insertSelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    List<Dish> selectByExample(DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    Dish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Dish record, @Param("example") DishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dish record);
}